run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  max-same-issues: 0

  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: duplicated-imports
        severity: warning
  importas:
    no-unaliased: true
    alias:
      # kcp operator
      - pkg: github.com/kcp-dev/kcp-operator/sdk/apis/(\w+)/(v[\w\d]+)
        alias: $1$2
      # Kubernetes
      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      # Controller Runtime (otherwise this will usually lead to shadowing a local "client" variable)
      - pkg: sigs.k8s.io/controller-runtime/pkg/client
        alias: ctrlruntimeclient
