---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers
  - frontproxies
  - shards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers/finalizers
  - frontproxies/finalizers
  - kubeconfigs/finalizers
  - rootshards/finalizers
  - shards/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - cacheservers/status
  - frontproxies/status
  - kubeconfigs/status
  - rootshards/status
  - shards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kcp.io
  resources:
  - kubeconfigs
  - rootshards
  verbs:
  - get
  - list
  - patch
  - update
  - watch
