apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeconfig-sample
spec:
  username: logical-cluster-admin
  groups:
    - system:kcp:logical-cluster-admin
    - system:masters
  validity: 8766h
  secretRef:
    name: sample-kubeconfig
  target:
    rootShardRef:
      name: shard-sample
