apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeconfig-sample
spec:
  username: user@kcp.io
  groups:
    - kcp-users
  validity: 8766h
  secretRef:
    name: sample-kubeconfig
  target:
    frontProxyRef:
      name: frontproxy-sample
    # rootShardRef:
    #   name: shard-sample
